# Generated by Django 3.2.5 on 2021-07-09 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thokoza', '0003_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='postal_code',
            new_name='state',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='province',
            new_name='zipcode',
        ),
    ]
