# Generated by Django 3.2.5 on 2021-08-17 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thokoza', '0008_alter_customer_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='transaction_id',
            field=models.FloatField(blank=True, max_length=300, null=True),
        ),
    ]
